GET http://localhost:3000/HomePage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiRmlyc3RfTmFtZSI6IkFhcm9uIiwiTGFzdF9OYW1lIjoiU2NoaWViZWwiLCJTa3lwZSI6MTIzNCwiTG9jYXRpb24iOiJCb3NuaWEgYW5kIEhlcnplZ292aW5hIiwidGltZVpvbmUiOiJFdXJvcGUvQmVsZ3JhZGUiLCJSb2xlIjoidGVzdCIsImlhdCI6MTY5MDgzMTAwMSwiZXhwIjoxNjkwOTE3NDAxfQ.rKO4XF-GvTcgggCEdsOrU2llMhUj-KaxSj6I0o-wTt0

###
POST https://codebluetimes.com/app/token
Content-Type: application/json

{ 
    "token":
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiRmlyc3RfTmFtZSI6IkFhcm9uIiwiTGFzdF9OYW1lIjoiU2NoaWViZWwiLCJTa3lwZSI6MTIzNCwiTG9jYXRpb25fSWQiOiIyNjUyNDUiLCJSb2xlIjoidGVzdCIsImlhdCI6MTY5MTUxNTkxNCwiZXhwIjoxNjk5MjkxOTE0fQ.TmsOIFK-3rX4FhbfSDntrOXH0E6zdIwxvDiPRF1Y_Zk"
   
}
####
POST http://localhost:3100/Email/ResetPassword
Content-Type: application/json

{
    "Email":"hi"
}

####
GET  https://codebluetimes.com
